services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: contacts_db
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  web:
    build: .
    container_name: flask_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
      MYSQL_DATABASE: contacts_db
      SECRET_KEY: my-very-secret-key
    depends_on:
      - db

volumes:
  db_data: